name: setup-dotnet-test

on:
  workflow_dispatch:
  push:

jobs:
  dotnet-action-test:
    runs-on: ubuntu-22-x64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.100
            8.0.100
      - run: |
          dotnet --version
