name: setup-dotnet-test

on:
  workflow_dispatch:
  push:

jobs:
  dotnet-action-test:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: DataDog/setup-dotnet@architecture2
        with:
          dotnet-version: '7.0.100'
          architecture: 'ppc64le'
      - run: |
          dotnet --version
