name: setup-dotnet-test

on:
  workflow_dispatch:
  push:

jobs:
  dotnet-action-test:
    runs-on: ubuntu-latest-ppc64le
    env:
      DOTNET_INSTALL_DIR: "/opt/dotnet"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - run: |
          dotnet --version
