name: setup-dotnet-test

on:
  workflow_dispatch:
  push:

jobs:
  dotnet-action-test:
    runs-on: ubuntu-latest-ppc64le
    strategy:
      matrix:
        dotnet: [ '7.0.115', '8.0.101' ]
    env:
      DOTNET_INSTALL_DIR: "/usr/lib64/dotnet"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: |
          echo '{"sdk":{"version": "${{ matrix.dotnet }}"}}' > ./global.json
          dotnet --version
