name: setup-dotnet-test

on:
  workflow_dispatch:
  push:

jobs:
  dotnet-action-test:
    runs-on: ubuntu-22-ppc64le
    env:
      DOTNET_INSTALL_DIR: "/opt/hostedtoolcache"
    steps:
      - uses: actions/checkout@v3
      - run: |
          dotnet --version
